import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  phoneMockup: {
    width: '300px',
    height: '600px',
    border: '12px solid #333',
    borderRadius: '40px',
    position: 'relative',
    background: 'white',
    overflow: 'hidden',
    boxShadow: '0 20px 50px rgba(0,0,0,0.2)',
  },
  notch: {
    position: 'absolute',
    top: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '120px',
    height: '25px',
    background: '#333',
    borderBottomLeftRadius: '12px',
    borderBottomRightRadius: '12px',
    zIndex: 20,
  },
  screen: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  statusBar: {
    height: '30px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 20px',
    paddingTop: '5px',
  },
  topbar: {
    width: '100%',
  },
  appContent: {
    flex: 1,
    overflowY: 'auto',
    position: 'relative',
    background: '#f9f9f9',
  },
  appHeader: {
    padding: '15px',
    background: 'white',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    boxShadow: '0 2px 5px rgba(0,0,0,0.05)',
  },
  logo: {
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  logoPlaceholder: {
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  banner: {
    height: '120px',
    background: '#e0e0e0',
    margin: '15px',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    padding: '0 15px',
    paddingBottom: '80px',
  },
  product: {
    background: 'white',
    padding: '10px',
    borderRadius: '8px',
    boxShadow: '0 2px 5px rgba(0,0,0,0.05)',
  },
  bottomNav: {
    height: '60px',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    fontSize: '18px',
  },
  navItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    fontSize: '11px',
  },
  navLabel: {
    fontSize: '9px',
    fontWeight: '600',
    marginTop: '2px',
  },
  homeBar: {
    width: '100px',
    height: '5px',
    background: '#ccc',
    borderRadius: '10px',
    margin: '10px auto',
    position: 'absolute',
    bottom: '5px',
    left: '0',
    right: '0',
  },
};
