// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
export const C = {
    brand:        '#4F46E5',
    brandLight:   '#EEF2FF',
    brandMuted:   '#818CF8',
    success:      '#059669',
    successBg:    '#F0FDF4',
    successBorder:'#A7F3D0',
    warning:      '#B45309',
    warningBg:    '#FFFBEB',
    warningBorder:'#FDE68A',
    danger:       '#B91C1C',
    dangerBg:     '#FFF5F5',
    dangerBorder: '#FECACA',
    neutralBorder:'#E5E7EB',
    neutralBg:    '#F9FAFB',
    neutralMid:   '#6B7280',
    neutralLight: '#9CA3AF',
    text:         '#111827',
    textMid:      '#374151',
    textSoft:     '#6B7280',
    white:        '#FFFFFF',
    dark:         '#111827',
};

// ─── TIPOGRAFIA — escala OneSignal ────────────────────────────────────────────
export const T = {
    xs:      '11px',
    sm:      '13px',
    base:    '14px',
    md:      '15px',
    lg:      '17px',
    xl:      '22px',
    xxl:     '28px',
    normal:  400,
    medium:  500,
    semibold:600,
    bold:    700,
    tight:   1.3,
    snug:    1.45,
    normal_lh: 1.6,
};
